"""Deterministic Texas Hold'em hand state and rules engine."""

from .cards import DECK, RANKS, RANK_VALUE, SUITS, evaluate, parse_cards, preflop_score
from .engine import apply_action, create_hand, deal_board, legal_actions
from .models import (
    ActionRecord,
    ActionType,
    GameConfig,
    HandState,
    LegalActions,
    PlayerState,
    PlayerStatus,
    Pot,
    Street,
    hand_from_dict,
    hand_to_dict,
    validate_state,
)
from .settlement import build_pots, settle_showdown
from .equity import EquityResult, sample_opponent_hands, simulate_weighted_equity
from .ranges import (
    BALANCED_PROFILE,
    LOOSE_AGGRESSIVE_PROFILE,
    TIGHT_PROFILE,
    OpponentProfile,
    WeightedRange,
    combo_class,
    filter_ranges_for_state,
    initialize_player_ranges,
    positions_by_seat,
    preflop_range,
    update_range_for_action,
    update_ranges_after_action,
)
from .strategy import (
    ActionAnalysis,
    CandidateAction,
    ResponseSummary,
    StrategyAnalysis,
    analyze_strategy,
    generate_candidate_actions,
    strategy_to_dict,
)

__all__ = [
    "ActionRecord",
    "ActionAnalysis",
    "ActionType",
    "CandidateAction",
    "DECK",
    "GameConfig",
    "HandState",
    "LegalActions",
    "LOOSE_AGGRESSIVE_PROFILE",
    "OpponentProfile",
    "PlayerState",
    "PlayerStatus",
    "Pot",
    "RANKS",
    "RANK_VALUE",
    "ResponseSummary",
    "Street",
    "StrategyAnalysis",
    "SUITS",
    "TIGHT_PROFILE",
    "BALANCED_PROFILE",
    "EquityResult",
    "WeightedRange",
    "apply_action",
    "analyze_strategy",
    "build_pots",
    "create_hand",
    "deal_board",
    "evaluate",
    "hand_from_dict",
    "hand_to_dict",
    "initialize_player_ranges",
    "legal_actions",
    "positions_by_seat",
    "parse_cards",
    "preflop_score",
    "preflop_range",
    "sample_opponent_hands",
    "settle_showdown",
    "simulate_weighted_equity",
    "strategy_to_dict",
    "combo_class",
    "filter_ranges_for_state",
    "generate_candidate_actions",
    "update_range_for_action",
    "update_ranges_after_action",
    "validate_state",
]
